### ISSUE TITLE
Problem running Windows package

### ISSUE THREAD

**Issue by etmunden** [jamesbarnett91/tplink-energy-monitor#21]
When I run the Windows package and try to open the page in Google Chrome (or Firefox) the energy monitor doesn't seem to display properly and doesn't show any data readings. It looks like this:
![isue2](https://user-images.githubusercontent.com/29552994/51403010-2c22f200-1b1d-11e9-9752-8e6a55f14067.PNG)
![issue3](https://user-images.githubusercontent.com/29552994/51403018-31803c80-1b1d-11e9-8cb5-1dc816da84b4.PNG)

This is what shows up in the command prompt:
![issue1](https://user-images.githubusercontent.com/29552994/51403037-39d87780-1b1d-11e9-80f6-3136cc65413c.PNG)

Any ideas?

**Comment by jamesbarnett91** [comment]
Hey thanks for the bug report.
Think the issue is the windows package doesn't have the logger config file included. 

I'll fix that in the next release, but in the mean time if you copy the contents of [this file](https://github.com/jamesbarnett91/tplink-energy-monitor/blob/master/logger-config.json) into a file called `logger-config.json` in the same folder as your `tplink-monitor-win.exe` file, that should fix that error.

Thanks

**Comment by etmunden** [comment]
Thanks, that fixed the error. 

However, I still am getting the same issue when I try and open the monitor in the browser and it still does not display properly, any ideas on this?

**Comment by arii** [comment]
I was working with @etmunden  on this.  We were trying to run this without our router offline. When the router was connected to the internet this issue was resolved.
